services:
  api:
    build:
      context: ../ServerApp
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    volumes:
      - ../ServerApp:/app
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ../clientapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ../clientapp:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://api:5000
    stdin_open: true
    tty: true
    command: sh -c "npm run dev"

    develop:
      watch:
        - action: sync
          path: ../clientapp
          target: /app

        - action: rebuild
          path: ../clientapp/Dockerfile
