#!/bin/bash
# =============================================================================
# Multi-Site Art Gallery Backup Cron Installation Script
# =============================================================================
# Usage: sudo ./install-backup-cron-multi.sh
#
# This script:
#   1. Creates /opt/artgallery/ directory structure
#   2. Copies multi-site backup/restore scripts to /opt/artgallery/scripts/
#   3. Sets up cron job for weekly backup (Sunday 2:00 AM)
#   4. Runs initial test backup for both sites
# =============================================================================

set -euo pipefail

# --- Configuration ---
INSTALL_DIR="/opt/artgallery"
SCRIPTS_DIR="$INSTALL_DIR/scripts"
BACKUP_DIR="$INSTALL_DIR/backups"
CRON_SCHEDULE="0 2 * * 0"  # Every Sunday at 2:00 AM

echo "========================================="
echo "Multi-Site Art Gallery Backup Installation"
echo "========================================="
echo ""

# --- Check if running as root ---
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run as root (use sudo)"
    exit 1
fi

# --- Determine source directory ---
SOURCE_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Source directory: $SOURCE_DIR"
echo "Install directory: $INSTALL_DIR"
echo ""

# --- Create directory structure ---
echo "Creating directory structure..."
mkdir -p "$SCRIPTS_DIR"
mkdir -p "$BACKUP_DIR"
chmod 755 "$BACKUP_DIR"

# --- Copy multi-site scripts ---
echo "Copying multi-site backup scripts..."
cp "$SOURCE_DIR/backup-multi.sh" "$SCRIPTS_DIR/backup-multi.sh"
cp "$SOURCE_DIR/restore-multi.sh" "$SCRIPTS_DIR/restore-multi.sh"
chmod +x "$SCRIPTS_DIR/backup-multi.sh"
chmod +x "$SCRIPTS_DIR/restore-multi.sh"

echo "Multi-site scripts installed:"
echo "  - $SCRIPTS_DIR/backup-multi.sh"
echo "  - $SCRIPTS_DIR/restore-multi.sh"
echo ""

# --- Also copy single-site scripts for compatibility ---
echo "Copying single-site backup scripts (for compatibility)..."
if [ -f "$SOURCE_DIR/backup.sh" ]; then
    cp "$SOURCE_DIR/backup.sh" "$SCRIPTS_DIR/backup.sh"
    chmod +x "$SCRIPTS_DIR/backup.sh"
fi
if [ -f "$SOURCE_DIR/restore.sh" ]; then
    cp "$SOURCE_DIR/restore.sh" "$SCRIPTS_DIR/restore.sh"
    chmod +x "$SCRIPTS_DIR/restore.sh"
fi
echo ""

# --- Create configuration file ---
echo "Creating configuration file..."

# Read password from docker-compose .env.multi file
ENV_FILE="$SOURCE_DIR/.env.multi"
if [ ! -f "$ENV_FILE" ]; then
    # Try .env as fallback
    ENV_FILE="$SOURCE_DIR/.env"
fi

if [ -f "$ENV_FILE" ]; then
    POSTGRES_PASSWORD=$(grep POSTGRES_PASSWORD "$ENV_FILE" | head -1 | cut -d'=' -f2)

    # Create config file for multi-site
    cat > "$SCRIPTS_DIR/backup.config" << EOF
# Art Gallery Multi-Site Backup Configuration
# Generated by install-backup-cron-multi.sh on $(date)
#
# IMPORTANT: This file contains sensitive data.
# Ensure permissions are set correctly (chmod 600).

POSTGRES_PASSWORD=$POSTGRES_PASSWORD
CONTAINER_NAME=artgallery-postgres
RETENTION_DAYS=30
EOF

    chmod 600 "$SCRIPTS_DIR/backup.config"
    echo "Configuration created: $SCRIPTS_DIR/backup.config"
else
    echo "WARNING: .env.multi file not found at $ENV_FILE"
    echo "Creating empty config template - you must fill in the password manually."

    cat > "$SCRIPTS_DIR/backup.config" << 'EOF'
# Art Gallery Multi-Site Backup Configuration
# Copy this file to backup.config and fill in your settings

POSTGRES_PASSWORD=YourStrongPassword!
CONTAINER_NAME=artgallery-postgres
RETENTION_DAYS=30
EOF

    chmod 600 "$SCRIPTS_DIR/backup.config"
    echo "Template created: $SCRIPTS_DIR/backup.config"
    echo "ACTION REQUIRED: Edit the config file and set your PostgreSQL password!"
    echo ""
    read -r -p "Press Enter after updating the password, or Ctrl+C to cancel..."
fi
echo ""

# --- Install cron job ---
echo "Installing cron job: $CRON_SCHEDULE (Sunday 2:00 AM)"

# Use crontab command for cross-distro compatibility
# Get existing root crontab if any, remove old backup entries, add new one
EXISTING_CRONTAB=$(crontab -l 2>/dev/null || true)
if [ -n "$EXISTING_CRONTAB" ]; then
    echo "$EXISTING_CRONTAB" | grep -v 'artgallery.*backup' | {
        cat
        echo "$CRON_SCHEDULE $SCRIPTS_DIR/backup-multi.sh"
    } | crontab -
else
    echo "$CRON_SCHEDULE $SCRIPTS_DIR/backup-multi.sh" | crontab -
fi

# Reload cron service
systemctl reload cron 2>/dev/null || service cron reload 2>/dev/null || true

echo "Cron job installed:"
crontab -l 2>/dev/null || echo "  (crontab list unavailable)"
echo ""

# --- Verify Docker is accessible ---
echo "Verifying Docker access..."
if ! docker info >/dev/null 2>&1; then
    echo "WARNING: Docker is not accessible. Backup will fail until Docker is running."
else
    echo "Docker is accessible."

    # Check if PostgreSQL container exists
    if docker ps -a --format '{{.Names}}' | grep -q "^artgallery-postgres$"; then
        echo "PostgreSQL container found: artgallery-postgres"
    else
        echo "WARNING: PostgreSQL container 'artgallery-postgres' not found."
        echo "Backup will fail until the container is running."
    fi
fi
echo ""

# --- Run test backup ---
echo "========================================="
echo "Running test backup..."
echo "========================================="

if docker ps --format '{{.Names}}' | grep -q "^artgallery-postgres$"; then
    if "$SCRIPTS_DIR/backup-multi.sh"; then
        echo ""
        echo "Test backup completed successfully!"
        echo ""
        echo "Backup files:"
        ls -lh "$BACKUP_DIR"/*.dump 2>/dev/null || echo "  (no backup files found)"
    else
        echo ""
        echo "WARNING: Test backup failed. Check logs at $BACKUP_DIR/backup.log"
    fi
else
    echo "Skipping test backup - PostgreSQL container not running."
fi

echo ""
echo "========================================="
echo "Installation Complete!"
echo "========================================="
echo ""
echo "Backup Schedule: Every Sunday at 2:00 AM"
echo "Backup Directory: $BACKUP_DIR"
echo "Log File: $BACKUP_DIR/backup.log"
echo ""
echo "Manual backup commands:"
echo "  Backup both sites:  $SCRIPTS_DIR/backup-multi.sh"
echo "  Backup GG only:     $SCRIPTS_DIR/backup-multi.sh gg"
echo "  Backup Flynn only:  $SCRIPTS_DIR/backup-multi.sh flynn"
echo ""
echo "Restore commands:"
echo "  Restore GG:   $SCRIPTS_DIR/restore-multi.sh gg [backup_file.dump]"
echo "  Restore Flynn: $SCRIPTS_DIR/restore-multi.sh flynn [backup_file.dump]"
echo ""
echo "To change backup schedule:"
echo "  crontab -e"
echo ""
