#!/bin/bash
# =============================================================================
# Art Gallery Backup Cron Installation Script
# =============================================================================
# Usage: sudo ./install-backup-cron.sh
#
# This script:
#   1. Creates /opt/artgallery/ directory structure
#   2. Copies backup/restore scripts to /opt/artgallery/scripts/
#   3. Sets up cron job for weekly backup (Sunday 2:00 AM)
#   4. Runs initial test backup
# =============================================================================

set -euo pipefail

# --- Configuration ---
INSTALL_DIR="/opt/artgallery"
SCRIPTS_DIR="$INSTALL_DIR/scripts"
BACKUP_DIR="$INSTALL_DIR/backups"
CRON_SCHEDULE="0 2 * * 0"  # Every Sunday at 2:00 AM

echo "========================================="
echo "Art Gallery Backup Installation"
echo "========================================="
echo ""

# --- Check if running as root ---
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run as root (use sudo)"
    exit 1
fi

# --- Determine source directory ---
# Script is run from docker-compose/scripts/
SOURCE_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Source directory: $SOURCE_DIR"
echo "Install directory: $INSTALL_DIR"
echo ""

# --- Create directory structure ---
echo "Creating directory structure..."
mkdir -p "$SCRIPTS_DIR"
mkdir -p "$BACKUP_DIR"
chmod 755 "$BACKUP_DIR"

# --- Copy scripts ---
echo "Copying backup scripts..."
cp "$SOURCE_DIR/backup.sh" "$SCRIPTS_DIR/backup.sh"
cp "$SOURCE_DIR/restore.sh" "$SCRIPTS_DIR/restore.sh"
chmod +x "$SCRIPTS_DIR/backup.sh"
chmod +x "$SCRIPTS_DIR/restore.sh"

echo "Scripts installed:"
echo "  - $SCRIPTS_DIR/backup.sh"
echo "  - $SCRIPTS_DIR/restore.sh"
echo ""

# --- Create configuration file ---
echo "Creating configuration file..."

# Read password from docker-compose .env file
ENV_FILE="$SOURCE_DIR/../.env"
if [ ! -f "$ENV_FILE" ]; then
    # Try parent directory
    ENV_FILE="$(cd "$SOURCE_DIR/../../" && pwd)/.env"
fi

if [ -f "$ENV_FILE" ]; then
    POSTGRES_PASSWORD=$(grep POSTGRES_PASSWORD "$ENV_FILE" | head -1 | cut -d'=' -f2)
    
    # Create config file
    cat > "$SCRIPTS_DIR/backup.config" << EOF
# Art Gallery Backup Configuration
# Generated by install-backup-cron.sh on $(date)
#
# IMPORTANT: This file contains sensitive data.
# Ensure permissions are set correctly (chmod 600).

POSTGRES_PASSWORD=$POSTGRES_PASSWORD
CONTAINER_NAME=artgallery-postgres-prod
DATABASE_NAME=artgallery
RETENTION_DAYS=30
EOF
    
    chmod 600 "$SCRIPTS_DIR/backup.config"
    echo "Configuration created: $SCRIPTS_DIR/backup.config"
else
    echo "WARNING: .env file not found at $ENV_FILE"
    echo "Creating empty config template - you must fill in the password manually."
    
    cat > "$SCRIPTS_DIR/backup.config" << 'EOF'
# Art Gallery Backup Configuration
# Copy this file to backup.config and fill in your settings

POSTGRES_PASSWORD=YourStrongPassword!
CONTAINER_NAME=artgallery-postgres-prod
DATABASE_NAME=artgallery
RETENTION_DAYS=120
EOF
    
    chmod 600 "$SCRIPTS_DIR/backup.config"
    echo "Template created: $SCRIPTS_DIR/backup.config"
    echo "ACTION REQUIRED: Edit the config file and set your PostgreSQL password!"
    echo ""
    read -r -p "Press Enter after updating the password, or Ctrl+C to cancel..."
fi
echo ""

# --- Install cron job ---
echo "Installing cron job: $CRON_SCHEDULE (Sunday 2:00 AM)"

# Use crontab command for cross-distro compatibility (Ubuntu uses /var/spool/cron/crontabs/, Debian uses /var/spool/cron/)
# Get existing root crontab if any, remove old backup entries, add new one
EXISTING_CRONTAB=$(crontab -l 2>/dev/null || true)
if [ -n "$EXISTING_CRONTAB" ]; then
    echo "$EXISTING_CRONTAB" | grep -v 'artgallery.*backup' | {
        cat
        echo "$CRON_SCHEDULE $SCRIPTS_DIR/backup.sh"
    } | crontab -
else
    echo "$CRON_SCHEDULE $SCRIPTS_DIR/backup.sh" | crontab -
fi

# Reload cron service
systemctl reload cron 2>/dev/null || service cron reload 2>/dev/null || true

echo "Cron job installed:"
crontab -l 2>/dev/null || echo "  (crontab list unavailable)"
echo ""

# --- Verify Docker is accessible ---
echo "Verifying Docker access..."
if ! docker info >/dev/null 2>&1; then
    echo "WARNING: Docker is not accessible. Backup will fail until Docker is running."
else
    echo "Docker is accessible."

    # Check if PostgreSQL container exists
    if docker ps -a --format '{{.Names}}' | grep -q "^artgallery-postgres-prod$"; then
        echo "PostgreSQL container found: artgallery-postgres-prod"
    else
        echo "WARNING: PostgreSQL container 'artgallery-postgres-prod' not found."
        echo "Backup will fail until the container is running."
    fi
fi
echo ""

# --- Run test backup ---
echo "========================================="
echo "Running test backup..."
echo "========================================="
echo ""

if "$SCRIPTS_DIR/backup.sh"; then
    echo ""
    echo "========================================="
    echo "TEST BACKUP SUCCESSFUL!"
    echo "========================================="
    echo ""
    echo "Backup directory: $BACKUP_DIR"
    echo "Weekly backup scheduled: Sunday at 2:00 AM"
    echo ""
    echo "Quick Reference:"
    echo "  Manual backup:  $SCRIPTS_DIR/backup.sh"
    echo "  Restore:        $SCRIPTS_DIR/restore.sh"
    echo "  View logs:      tail -f $BACKUP_DIR/backup.log"
    echo "  List backups:   ls -lh $BACKUP_DIR/*.dump"
    echo "  Cron schedule:  crontab -l"
    echo ""
else
    echo ""
    echo "========================================="
    echo "TEST BACKUP FAILED!"
    echo "========================================="
    echo ""
    echo "Check the log for details:"
    echo "  tail -f $BACKUP_DIR/backup.log"
    echo ""
    echo "Common issues:"
    echo "  - Docker not running"
    echo "  - PostgreSQL container not started"
    echo "  - Docker secrets not available"
    echo "  - Insufficient permissions"
    echo ""
    exit 1
fi

exit 0
