export interface Painting {
    id: string;
    slug: string;
    title: string;
    description?: string;
    imageUrl: string;
    thumbnailUrl?: string;
    categorySlug: string;
    width?: number;
    height?: number;
    depth?: number;
    year?: number;
    price?: number;
    isAvailable: boolean;
}

// Dummy data for all paintings - will be replaced with API data
export const paintingsData: Painting[] = [
    // Landscapes and Cityscapes
    {
        id: 'landscape-1',
        slug: 'aspens',
        title: 'Aspens',
        description: 'A serene autumn scene featuring golden aspen trees against a mountain backdrop.',
        imageUrl: '/Landscapes and Cityscapes/Aspens.jpg',
        categorySlug: 'landscapes-and-cityscapes',
        width: 24,
        height: 36,
        year: 2023,
        price: 1200,
        isAvailable: true
    },
    {
        id: 'landscape-2',
        slug: 'bahia-honda',
        title: 'Bahia Honda',
        description: 'A tropical paradise capturing the essence of the Florida Keys.',
        imageUrl: '/Landscapes and Cityscapes/Bahia Honda .jpg',
        categorySlug: 'landscapes-and-cityscapes',
        width: 30,
        height: 40,
        year: 2022,
        price: 1500,
        isAvailable: true
    },
    {
        id: 'landscape-3',
        slug: 'baked-goods',
        title: 'Baked Goods',
        description: 'A charming street scene featuring a local bakery.',
        imageUrl: '/Landscapes and Cityscapes/BakedGoods.JPG',
        categorySlug: 'landscapes-and-cityscapes',
        width: 18,
        height: 24,
        year: 2023,
        price: 800,
        isAvailable: false
    },
    {
        id: 'landscape-4',
        slug: 'banyans',
        title: 'Banyans',
        description: 'Majestic banyan trees creating a natural cathedral.',
        imageUrl: '/Landscapes and Cityscapes/Banyans.jpg',
        categorySlug: 'landscapes-and-cityscapes',
        width: 36,
        height: 48,
        year: 2022,
        price: 2000,
        isAvailable: true
    },
    {
        id: 'landscape-5',
        slug: 'brady-and-duke',
        title: 'Brady & Duke',
        description: 'A heartwarming portrait of two beloved companions.',
        imageUrl: '/Landscapes and Cityscapes/Brady & Duke.jpg',
        categorySlug: 'landscapes-and-cityscapes',
        width: 20,
        height: 24,
        year: 2023,
        price: 950,
        isAvailable: true
    },
    {
        id: 'landscape-6',
        slug: 'bridge-world',
        title: 'Bridge World',
        description: 'An architectural study of bridges connecting worlds.',
        imageUrl: '/Landscapes and Cityscapes/Bridge world.jpg',
        categorySlug: 'landscapes-and-cityscapes',
        width: 24,
        height: 30,
        year: 2021,
        price: 1100,
        isAvailable: true
    },
    {
        id: 'landscape-7',
        slug: 'castelvetore',
        title: 'Castelvetore',
        description: 'A picturesque Italian village bathed in warm sunlight.',
        imageUrl: '/Landscapes and Cityscapes/Castelvetore .JPG',
        categorySlug: 'landscapes-and-cityscapes',
        width: 20,
        height: 28,
        year: 2022,
        price: 1300,
        isAvailable: true
    },
    {
        id: 'landscape-8',
        slug: 'cobblestone-way',
        title: 'Cobblestone Way',
        description: 'An old-world charm captured in cobblestone streets.',
        imageUrl: '/Landscapes and Cityscapes/Cobblestone Way.JPG',
        categorySlug: 'landscapes-and-cityscapes',
        width: 16,
        height: 20,
        year: 2023,
        price: 750,
        isAvailable: false
    },
    {
        id: 'landscape-9',
        slug: 'forest-mystery',
        title: 'Forest Mystery',
        description: 'Enigmatic forest scene with dappled light filtering through trees.',
        imageUrl: '/Landscapes and Cityscapes/Forest Mystery.jpg',
        categorySlug: 'landscapes-and-cityscapes',
        width: 30,
        height: 36,
        year: 2022,
        price: 1600,
        isAvailable: true
    },
    {
        id: 'landscape-10',
        slug: 'hydrangea-time',
        title: 'Hydrangea Time',
        description: 'Lush hydrangeas in full bloom creating a garden paradise.',
        imageUrl: '/Landscapes and Cityscapes/Hydrangea Time.jpeg',
        categorySlug: 'landscapes-and-cityscapes',
        width: 24,
        height: 24,
        year: 2023,
        price: 900,
        isAvailable: true
    },
    {
        id: 'landscape-11',
        slug: 'italian-church',
        title: 'Italian Church',
        description: 'A historic church standing as a testament to faith and artistry.',
        imageUrl: '/Landscapes and Cityscapes/Italian Church.jpg',
        categorySlug: 'landscapes-and-cityscapes',
        width: 28,
        height: 36,
        year: 2021,
        price: 1400,
        isAvailable: true
    },
    {
        id: 'landscape-12',
        slug: 'mine',
        title: 'Mine',
        description: 'An industrial landscape exploring the beauty of working environments.',
        imageUrl: '/Landscapes and Cityscapes/Mine (1).jpg',
        categorySlug: 'landscapes-and-cityscapes',
        width: 32,
        height: 40,
        year: 2022,
        price: 1700,
        isAvailable: false
    },
    {
        id: 'landscape-13',
        slug: 'new-inhabitants',
        title: 'New Inhabitants',
        description: 'Nature reclaiming space with new life emerging.',
        imageUrl: '/Landscapes and Cityscapes/New Inhabitants.jpeg',
        categorySlug: 'landscapes-and-cityscapes',
        width: 20,
        height: 24,
        year: 2023,
        price: 850,
        isAvailable: true
    },
    {
        id: 'landscape-14',
        slug: 'rainbow-river',
        title: 'Rainbow River',
        description: 'A vibrant river scene with colorful reflections.',
        imageUrl: '/Landscapes and Cityscapes/Rainbow River1.jpg',
        categorySlug: 'landscapes-and-cityscapes',
        width: 24,
        height: 32,
        year: 2022,
        price: 1250,
        isAvailable: true
    },
    {
        id: 'landscape-15',
        slug: 'sedona',
        title: 'Sedona',
        description: 'The iconic red rocks of Sedona in golden hour light.',
        imageUrl: '/Landscapes and Cityscapes/Sedona.JPG',
        categorySlug: 'landscapes-and-cityscapes',
        width: 30,
        height: 40,
        year: 2021,
        price: 1800,
        isAvailable: true
    },
    {
        id: 'landscape-16',
        slug: 'the-path',
        title: 'The Path',
        description: 'A winding path inviting viewers into a contemplative journey.',
        imageUrl: '/Landscapes and Cityscapes/The Path.jpg',
        categorySlug: 'landscapes-and-cityscapes',
        width: 24,
        height: 30,
        year: 2023,
        price: 1100,
        isAvailable: true
    },
    {
        id: 'landscape-17',
        slug: 'the-pond',
        title: 'The Pond',
        description: 'A tranquil pond reflecting the surrounding nature.',
        imageUrl: '/Landscapes and Cityscapes/The Pond.jpg',
        categorySlug: 'landscapes-and-cityscapes',
        width: 20,
        height: 28,
        year: 2022,
        price: 950,
        isAvailable: false
    },
    {
        id: 'landscape-18',
        slug: 'window-jigsaw',
        title: 'Window Jigsaw',
        description: 'An abstract view through windows creating a puzzle of perspectives.',
        imageUrl: '/Landscapes and Cityscapes/Window Jigsaw.jpg',
        categorySlug: 'landscapes-and-cityscapes',
        width: 18,
        height: 24,
        year: 2023,
        price: 800,
        isAvailable: true
    },
    // Seascapes
    {
        id: 'seascape-1',
        slug: 'cloud-creatures',
        title: 'Cloud Creatures',
        description: 'Whimsical cloud formations dancing across the sky above the ocean.',
        imageUrl: '/Seascapes/Cloud Creatures2.jpg',
        categorySlug: 'seascapes',
        width: 30,
        height: 40,
        year: 2023,
        price: 1600,
        isAvailable: true
    },
    {
        id: 'seascape-2',
        slug: 'contemplation',
        title: 'Contemplation',
        description: 'A moment of quiet reflection by the waters edge.',
        imageUrl: '/Seascapes/Contemplation.jpeg',
        categorySlug: 'seascapes',
        width: 24,
        height: 32,
        year: 2022,
        price: 1200,
        isAvailable: true
    },
    {
        id: 'seascape-3',
        slug: 'double-roll',
        title: 'Double Roll',
        description: 'Two waves rolling in perfect harmony toward the shore.',
        imageUrl: '/Seascapes/Double Roll.jpg',
        categorySlug: 'seascapes',
        width: 36,
        height: 48,
        year: 2021,
        price: 2200,
        isAvailable: false
    },
    {
        id: 'seascape-4',
        slug: 'even-cloudy-days-are-better-at-the-beach',
        title: 'Even Cloudy Days are Better at the Beach',
        description: 'Finding beauty in overcast coastal scenes.',
        imageUrl: '/Seascapes/Even Cloudy Days are Better at the Beach.jpeg',
        categorySlug: 'seascapes',
        width: 24,
        height: 30,
        year: 2023,
        price: 1100,
        isAvailable: true
    },
    {
        id: 'seascape-5',
        slug: 'mangrove-village',
        title: 'Mangrove Village',
        description: 'A coastal village nestled among mangrove trees.',
        imageUrl: '/Seascapes/Mangrove Village.jpg',
        categorySlug: 'seascapes',
        width: 28,
        height: 36,
        year: 2022,
        price: 1400,
        isAvailable: true
    },
    {
        id: 'seascape-6',
        slug: 'morning-glory',
        title: 'Morning Glory',
        description: 'The first light of dawn breaking over the ocean.',
        imageUrl: '/Seascapes/Morning Glory.jpg',
        categorySlug: 'seascapes',
        width: 30,
        height: 40,
        year: 2023,
        price: 1700,
        isAvailable: true
    },
    {
        id: 'seascape-7',
        slug: 'pastel-morning',
        title: 'Pastel Morning',
        description: 'Soft pastel hues painting the early morning sky.',
        imageUrl: '/Seascapes/Pastel Morning.JPG',
        categorySlug: 'seascapes',
        width: 24,
        height: 32,
        year: 2022,
        price: 1250,
        isAvailable: true
    },
    {
        id: 'seascape-8',
        slug: 'rainbow-river',
        title: 'Rainbow River',
        description: 'Where the river meets the sea in a colorful embrace.',
        imageUrl: '/Seascapes/Rainbow River.jpg',
        categorySlug: 'seascapes',
        width: 26,
        height: 34,
        year: 2021,
        price: 1350,
        isAvailable: false
    },
    {
        id: 'seascape-9',
        slug: 'rowboat-waiting',
        title: 'Rowboat Waiting',
        description: 'A solitary rowboat resting on calm waters.',
        imageUrl: '/Seascapes/Rowboat Waiting.jpg',
        categorySlug: 'seascapes',
        width: 20,
        height: 28,
        year: 2023,
        price: 950,
        isAvailable: true
    },
    {
        id: 'seascape-10',
        slug: 'sailboat',
        title: 'Sailboat',
        description: 'A graceful sailboat cutting through the waves.',
        imageUrl: '/Seascapes/Sailboat.jpg',
        categorySlug: 'seascapes',
        width: 24,
        height: 30,
        year: 2022,
        price: 1150,
        isAvailable: true
    },
    {
        id: 'seascape-11',
        slug: 'sailing-sunset',
        title: 'Sailing Sunset',
        description: 'Silhouetted sails against a dramatic sunset.',
        imageUrl: '/Seascapes/Sailing Sunset.jpg',
        categorySlug: 'seascapes',
        width: 32,
        height: 40,
        year: 2021,
        price: 1800,
        isAvailable: true
    },
    {
        id: 'seascape-12',
        slug: 'seeing-red',
        title: 'Seeing Red',
        description: 'Bold red tones capturing the intensity of coastal light.',
        imageUrl: '/Seascapes/Seeing Red.jpg',
        categorySlug: 'seascapes',
        width: 24,
        height: 32,
        year: 2023,
        price: 1200,
        isAvailable: true
    },
    {
        id: 'seascape-13',
        slug: 'shore-scene',
        title: 'Shore Scene',
        description: 'A peaceful shoreline with gentle waves lapping at the sand.',
        imageUrl: '/Seascapes/Shore scene.JPG',
        categorySlug: 'seascapes',
        width: 20,
        height: 24,
        year: 2022,
        price: 900,
        isAvailable: false
    },
    {
        id: 'seascape-14',
        slug: 'solitude',
        title: 'Solitude',
        description: 'The peaceful isolation of being alone with the ocean.',
        imageUrl: '/Seascapes/Solitude.jpg',
        categorySlug: 'seascapes',
        width: 28,
        height: 36,
        year: 2023,
        price: 1450,
        isAvailable: true
    },
    {
        id: 'seascape-15',
        slug: 'sunrise-drama',
        title: 'Sunrise Drama',
        description: 'Dramatic clouds and light at the moments of sunrise.',
        imageUrl: '/Seascapes/SunriseDrama.JPG',
        categorySlug: 'seascapes',
        width: 30,
        height: 40,
        year: 2022,
        price: 1650,
        isAvailable: true
    },
    {
        id: 'seascape-16',
        slug: 'wave-blue',
        title: 'Wave Blue',
        description: 'The deep blue of ocean waves in motion.',
        imageUrl: '/Seascapes/Wave Blue.jpg',
        categorySlug: 'seascapes',
        width: 24,
        height: 30,
        year: 2021,
        price: 1100,
        isAvailable: true
    },
    {
        id: 'seascape-17',
        slug: 'wind-and-water',
        title: 'Wind and Water',
        description: 'The dynamic interplay between wind and water.',
        imageUrl: '/Seascapes/Wind and Water1.JPG',
        categorySlug: 'seascapes',
        width: 26,
        height: 34,
        year: 2023,
        price: 1300,
        isAvailable: true
    },
    // Animals
    {
        id: 'animal-1',
        slug: 'abbys-horse',
        title: 'Abby\'s Horse',
        description: 'A majestic portrait of Abby\'s beloved horse.',
        imageUrl: '/Animals/Abby\'s Horse.jpg',
        categorySlug: 'animals-and-people',
        width: 30,
        height: 40,
        year: 2023,
        price: 1800,
        isAvailable: true
    },
    {
        id: 'animal-2',
        slug: 'angelfish-and-purple-fan',
        title: 'Angelfish & Purple Fan',
        description: 'Vibrant underwater scene featuring colorful angelfish.',
        imageUrl: '/Animals/Angelfish  & Purple Fan.jpg',
        categorySlug: 'animals-and-people',
        width: 24,
        height: 32,
        year: 2022,
        price: 1400,
        isAvailable: true
    },
    {
        id: 'animal-3',
        slug: 'cruising',
        title: 'Cruising',
        description: 'Marine life cruising through the ocean depths.',
        imageUrl: '/Animals/Cruising.JPG',
        categorySlug: 'animals-and-people',
        width: 20,
        height: 28,
        year: 2023,
        price: 1100,
        isAvailable: false
    },
    {
        id: 'animal-4',
        slug: 'dyptych-big-yellow',
        title: 'Dyptych Big Yellow',
        description: 'A striking dyptych featuring bold yellow tones.',
        imageUrl: '/Animals/Dyptych Big Yellow.jpg',
        categorySlug: 'animals-and-people',
        width: 36,
        height: 48,
        year: 2021,
        price: 2400,
        isAvailable: true
    },
    {
        id: 'animal-5',
        slug: 'dyptych-ocean-butterflies',
        title: 'Dyptych Ocean Butterflies',
        description: 'Two panels capturing the grace of ocean butterflies.',
        imageUrl: '/Animals/Dyptych Ocean butterflies.jpg',
        categorySlug: 'animals-and-people',
        width: 40,
        height: 30,
        year: 2022,
        price: 2200,
        isAvailable: true
    },
    {
        id: 'animal-6',
        slug: 'ever-vigilant',
        title: 'Ever Vigilant',
        description: 'A watchful creature ever alert to its surroundings.',
        imageUrl: '/Animals/Ever Vigilant.jpg',
        categorySlug: 'animals-and-people',
        width: 24,
        height: 30,
        year: 2023,
        price: 1250,
        isAvailable: true
    },
    {
        id: 'animal-7',
        slug: 'fairy-wrens',
        title: 'Fairy Wrens',
        description: 'Delicate fairy wrens in their natural habitat.',
        imageUrl: '/Animals/Fairy Wrens.jpg',
        categorySlug: 'animals-and-people',
        width: 18,
        height: 24,
        year: 2022,
        price: 850,
        isAvailable: true
    },
    {
        id: 'animal-8',
        slug: 'green-turtle',
        title: 'Green Turtle',
        description: 'A serene green turtle gliding through turquoise waters.',
        imageUrl: '/Animals/Green Turtle.JPG',
        categorySlug: 'animals-and-people',
        width: 28,
        height: 36,
        year: 2021,
        price: 1600,
        isAvailable: false
    },
    {
        id: 'animal-9',
        slug: 'hiding',
        title: 'Hiding',
        description: 'A playful creature caught in a moment of hiding.',
        imageUrl: '/Animals/Hiding.JPG',
        categorySlug: 'animals-and-people',
        width: 20,
        height: 24,
        year: 2023,
        price: 950,
        isAvailable: true
    },
    {
        id: 'animal-10',
        slug: 'leatherback',
        title: 'Leatherback',
        description: 'The magnificent leatherback turtle in its element.',
        imageUrl: '/Animals/Leatherback .jpg',
        categorySlug: 'animals-and-people',
        width: 32,
        height: 40,
        year: 2022,
        price: 1750,
        isAvailable: true
    },
    {
        id: 'animal-11',
        slug: 'manatees',
        title: 'Manatees',
        description: 'Gentle manatees floating in peaceful waters.',
        imageUrl: '/Animals/Manatees.jpg',
        categorySlug: 'animals-and-people',
        width: 24,
        height: 32,
        year: 2023,
        price: 1300,
        isAvailable: true
    },
    {
        id: 'animal-12',
        slug: 'meadow',
        title: 'Meadow',
        description: 'Wild animals grazing in a sunlit meadow.',
        imageUrl: '/Animals/Meadow.JPG',
        categorySlug: 'animals-and-people',
        width: 30,
        height: 40,
        year: 2022,
        price: 1550,
        isAvailable: true
    },
    {
        id: 'animal-13',
        slug: 'my-green-visitor',
        title: 'My Green Visitor',
        description: 'An unexpected green visitor bringing life to the scene.',
        imageUrl: '/Animals/My Green Visitor.jpg',
        categorySlug: 'animals-and-people',
        width: 20,
        height: 28,
        year: 2021,
        price: 1050,
        isAvailable: false
    },
    {
        id: 'animal-14',
        slug: 'octopus-purple',
        title: 'Octopus Purple',
        description: 'A mesmerizing purple octopus in all its tentacled glory.',
        imageUrl: '/Animals/OctopusPurple.jpg',
        categorySlug: 'animals-and-people',
        width: 24,
        height: 24,
        year: 2023,
        price: 1150,
        isAvailable: true
    },
    {
        id: 'animal-15',
        slug: 'painted-bunting',
        title: 'Painted Bunting',
        description: 'The brilliantly colored painted bunting in flight.',
        imageUrl: '/Animals/Painted Bunting .jpg',
        categorySlug: 'animals-and-people',
        width: 16,
        height: 20,
        year: 2022,
        price: 750,
        isAvailable: true
    },
    {
        id: 'animal-16',
        slug: 'peekaboo',
        title: 'Peekaboo',
        description: 'A playful peekaboo moment with a curious creature.',
        imageUrl: '/Animals/Peekaboo.jpg',
        categorySlug: 'animals-and-people',
        width: 18,
        height: 24,
        year: 2023,
        price: 850,
        isAvailable: true
    },
    {
        id: 'animal-17',
        slug: 'sam',
        title: 'Sam',
        description: 'A portrait of Sam, a beloved companion.',
        imageUrl: '/Animals/Sam.JPG',
        categorySlug: 'animals-and-people',
        width: 20,
        height: 24,
        year: 2022,
        price: 900,
        isAvailable: false
    },
    {
        id: 'animal-18',
        slug: 'snail-kite',
        title: 'Snail Kite',
        description: 'The elegant snail kite in its natural wetland habitat.',
        imageUrl: '/Animals/Snail Kite .jpg',
        categorySlug: 'animals-and-people',
        width: 24,
        height: 30,
        year: 2021,
        price: 1200,
        isAvailable: true
    },
    {
        id: 'animal-19',
        slug: 'snowy-owl',
        title: 'Snowy Owl',
        description: 'A majestic snowy owl with piercing gaze.',
        imageUrl: '/Animals/SnowyOwl.jpg',
        categorySlug: 'animals-and-people',
        width: 28,
        height: 36,
        year: 2023,
        price: 1650,
        isAvailable: true
    },
    {
        id: 'animal-20',
        slug: 'spiny-lobster',
        title: 'Spiny Lobster',
        description: 'A colorful spiny lobster in its underwater world.',
        imageUrl: '/Animals/Spiny Lobster.jpg',
        categorySlug: 'animals-and-people',
        width: 20,
        height: 28,
        year: 2022,
        price: 1050,
        isAvailable: true
    },
    {
        id: 'animal-21',
        slug: 'tigers',
        title: 'Tigers',
        description: 'The power and grace of tigers captured in paint.',
        imageUrl: '/Animals/Tigers.jpg',
        categorySlug: 'animals-and-people',
        width: 36,
        height: 48,
        year: 2021,
        price: 2500,
        isAvailable: true
    },
    {
        id: 'animal-22',
        slug: 'to-the-light',
        title: 'To the Light',
        description: 'Creatures drawn to the light in a dramatic scene.',
        imageUrl: '/Animals/To the Light.jpg',
        categorySlug: 'animals-and-people',
        width: 24,
        height: 32,
        year: 2023,
        price: 1350,
        isAvailable: false
    },
    {
        id: 'animal-23',
        slug: 'whats-for-dinner',
        title: 'What\'s for Dinner',
        description: 'A humorous take on the food chain in nature.',
        imageUrl: '/Animals/What\'s for dinner.jpg',
        categorySlug: 'animals-and-people',
        width: 22,
        height: 28,
        year: 2022,
        price: 1100,
        isAvailable: true
    },
    {
        id: 'animal-24',
        slug: 'wild-white-majesty',
        title: 'Wild White Majesty',
        description: 'The wild white majesty of nature\'s creatures.',
        imageUrl: '/Animals/Wild White Majesty.jpg',
        categorySlug: 'animals-and-people',
        width: 30,
        height: 40,
        year: 2021,
        price: 1800,
        isAvailable: true
    },
    {
        id: 'animal-25',
        slug: 'zsazsa',
        title: 'ZsaZsa',
        description: 'A charming portrait of ZsaZsa with personality.',
        imageUrl: '/Animals/ZsaZsa.jpeg',
        categorySlug: 'animals-and-people',
        width: 18,
        height: 24,
        year: 2023,
        price: 850,
        isAvailable: true
    },
    // Flowers
    {
        id: 'flower-1',
        slug: 'bird-of-paradise',
        title: 'Bird of Paradise',
        description: 'The exotic beauty of the bird of paradise flower.',
        imageUrl: '/Flowers/Bird of Paradise.jpg',
        categorySlug: 'flowers',
        width: 24,
        height: 30,
        year: 2023,
        price: 1200,
        isAvailable: true
    },
    {
        id: 'flower-2',
        slug: 'bumblebee',
        title: 'Bumblebee',
        description: 'A busy bumblebee collecting nectar from vibrant blooms.',
        imageUrl: '/Flowers/Bumblebee.jpg',
        categorySlug: 'flowers',
        width: 20,
        height: 24,
        year: 2022,
        price: 950,
        isAvailable: true
    },
    {
        id: 'flower-3',
        slug: 'coneflowers',
        title: 'Coneflowers',
        description: 'Rustic coneflowers swaying in a summer breeze.',
        imageUrl: '/Flowers/Coneflowers.jpg',
        categorySlug: 'flowers',
        width: 24,
        height: 32,
        year: 2023,
        price: 1150,
        isAvailable: false
    },
    {
        id: 'flower-4',
        slug: 'daffodils',
        title: 'Daffodils',
        description: 'Cheerful daffodils heralding the arrival of spring.',
        imageUrl: '/Flowers/Daffodils.jpg',
        categorySlug: 'flowers',
        width: 20,
        height: 28,
        year: 2022,
        price: 1000,
        isAvailable: true
    },
    {
        id: 'flower-5',
        slug: 'flowers-for-dee',
        title: 'Flowers for Dee',
        description: 'A special floral tribute created for Dee.',
        imageUrl: '/Flowers/Flowers for Dee.jpg',
        categorySlug: 'flowers',
        width: 24,
        height: 30,
        year: 2021,
        price: 1250,
        isAvailable: true
    },
    {
        id: 'flower-6',
        slug: 'honey-bee',
        title: 'Honey Bee',
        description: 'A honey bee at work among colorful blossoms.',
        imageUrl: '/Flowers/Honey bee.jpeg',
        categorySlug: 'flowers',
        width: 18,
        height: 24,
        year: 2023,
        price: 850,
        isAvailable: true
    },
    {
        id: 'flower-7',
        slug: 'milkweed-hummingbird',
        title: 'Milkweed Hummingbird',
        description: 'A hummingbird feeding on milkweed nectar.',
        imageUrl: '/Flowers/MilkweedHummingbird.jpg',
        categorySlug: 'flowers',
        width: 22,
        height: 28,
        year: 2022,
        price: 1100,
        isAvailable: true
    },
    {
        id: 'flower-8',
        slug: 'monarch-beginnings',
        title: 'Monarch Beginnings',
        description: 'The beginning of a monarch butterfly\'s journey.',
        imageUrl: '/Flowers/Monarch Beginnings.JPG',
        categorySlug: 'flowers',
        width: 20,
        height: 24,
        year: 2023,
        price: 950,
        isAvailable: false
    },
    {
        id: 'flower-9',
        slug: 'royal-poinciana',
        title: 'Royal Poinciana',
        description: 'The regal royal poinciana in full tropical bloom.',
        imageUrl: '/Flowers/Royal Poinciana.jpg',
        categorySlug: 'flowers',
        width: 28,
        height: 36,
        year: 2021,
        price: 1500,
        isAvailable: true
    },
    {
        id: 'flower-10',
        slug: 'squash-blossoms',
        title: 'Squash Blossoms',
        description: 'Golden squash blossoms in a garden setting.',
        imageUrl: '/Flowers/Squash blossoms1.JPG',
        categorySlug: 'flowers',
        width: 20,
        height: 24,
        year: 2022,
        price: 900,
        isAvailable: true
    },
    {
        id: 'flower-11',
        slug: 'the-bee',
        title: 'The Bee',
        description: 'A close-up study of a bee in its natural habitat.',
        imageUrl: '/Flowers/The Bee.jpg',
        categorySlug: 'flowers',
        width: 16,
        height: 20,
        year: 2023,
        price: 750,
        isAvailable: true
    },
    {
        id: 'flower-12',
        slug: 'water-lilies',
        title: 'Water Lilies',
        description: 'Peaceful water lilies floating on a tranquil pond.',
        imageUrl: '/Flowers/Water lilies.jpg',
        categorySlug: 'flowers',
        width: 24,
        height: 32,
        year: 2022,
        price: 1200,
        isAvailable: true
    }
];

// Helper function to get painting by ID
export function getPaintingById(id: string): Painting | undefined {
    return paintingsData.find(painting => painting.id === id);
}

// Helper function to get paintings by category
export function getPaintingsByCategory(categorySlug: string): Painting[] {
    return paintingsData.filter(painting => painting.categorySlug === categorySlug);
}

// Helper function to format dimensions for display
export function formatDimensions(painting: Painting): string {
    if (painting.width && painting.height) {
        if (painting.depth) {
            return `${painting.width}x${painting.height}x${painting.depth} inches`;
        }
        return `${painting.width}x${painting.height} inches`;
    }
    return '';
}